"""create commands and main_commands

Revision ID: f982f0c13497
Revises:
Create Date: 2026-09-08 16:14:44.253046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f982f0c13497'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Kept in sync with app.database.models.SCHEMA_NAME. Migrations are snapshots of the
# schema at a point in time, so they hardcode the name rather than importing it.
SCHEMA_NAME = "gs"

# Postgres keeps an ENUM type around after its table is dropped, so the type has to be
# dropped explicitly in downgrade(). create_table() creates it implicitly in upgrade().
command_status = sa.Enum(
    'PENDING', 'SCHEDULED', 'ONGOING', 'CANCELLED', 'FAILED', 'COMPLETED',
    name='commandstatus',
)


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(f"CREATE SCHEMA IF NOT EXISTS {SCHEMA_NAME}")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('main_commands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('params', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('format', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data_size', sa.Integer(), nullable=False),
    sa.Column('total_size', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema=SCHEMA_NAME
    )
    op.create_index(op.f('ix_gs_main_commands_id'), 'main_commands', ['id'], unique=False, schema=SCHEMA_NAME)
    op.create_table('commands',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', command_status, nullable=False),
    sa.Column('type_', sa.Integer(), nullable=False),
    sa.Column('params', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['type_'], [f'{SCHEMA_NAME}.main_commands.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema=SCHEMA_NAME
    )
    op.create_index(op.f('ix_gs_commands_id'), 'commands', ['id'], unique=False, schema=SCHEMA_NAME)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gs_commands_id'), table_name='commands', schema=SCHEMA_NAME)
    op.drop_table('commands', schema=SCHEMA_NAME)
    op.drop_index(op.f('ix_gs_main_commands_id'), table_name='main_commands', schema=SCHEMA_NAME)
    op.drop_table('main_commands', schema=SCHEMA_NAME)
    # ### end Alembic commands ###

    command_status.drop(op.get_bind(), checkfirst=True)
    op.execute(f"DROP SCHEMA IF EXISTS {SCHEMA_NAME} RESTRICT")
